name = "KeMontielOleaNesbit2024"
uuid = "7910306a-e9c1-4799-8892-8a3b0c1683a8"
authors = ["Kacper Krasowski, Stefano Fusinato"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDFIO = "4d0d745f-9d9a-592e-8d18-1ad8a0f42b92"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StopWords = "35248bf2-58a5-46a0-9b1d-c0a73a50a107"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"
WordCloud = "6385f0a0-cb03-45b6-9089-4e0acc74b26b"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
DataStructures = "0.18.22"
Distributions = "0.25.120"
JLD2 = "0.5.13"
JSON = "0.21.4"
KernelDensity = "0.6.9"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
PDFIO = "0.1.15"
Plots = "1.40.13"
Printf = "1.11.0"
Random = "1.11.0"
SpecialFunctions = "2.5.1"
Statistics = "1.11.1"
StatsPlots = "0.15.7"
StopWords = "1.0.1"
Test = "1.11.0"
TextAnalysis = "0.8.2"
WordCloud = "1.3.2"
XLSX = "0.10.4"
julia = "1.11.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
